### PR TITLE
@orta => Escapes HTML in feed.

### PR DESCRIPTION
**Pull request by ashfurrow**
This is the best I could do. It validates!

### CODE REVIEW

**Comment by dblock** [comment]
I think this needs to be `xml_escape`, its implementation is:

``` ruby
def xml_escape(input)
  CGI.escapeHTML(input.to_s)
end
```

See https://github.com/jekyll/jekyll/issues/2026.

**Comment by ashfurrow** [comment]
I tried that but the implementation doesn't actually escape the XML tags. So "&lt;ul&gt;..." just stays that way.

**Comment by dblock** [comment]
Are you sure? Their own example says it should:

```
xml_escape('foo "bar" <baz>')
    #   # => "foo &quot;bar&quot; &lt;baz&gt;"
```

How do I see this happen?

**Comment by ashfurrow** [comment]
Ah, no, you're right. Made the mistake of confusing Chrome's XML parser with the browser itself parsing the `&lt;`s.

**Comment by dblock** [comment]
Danke.

**Pull request merged**
