### PR TITLE
Add GH link for CPKenburnsView

### PR DESCRIPTION
**Pull request by mrh-is**

### CODE REVIEW

**Comment by dblock** [comment]
Thanks. Make sure the pod has the right URL in its podspec, too. We generate this list from that.

**Comment by mrh-is** [comment]
Maybe there should also be a link to the GH repo for every pod? That way main link will be to the homepage the author specified, but there will also be a canonical way to get to the repo.

**Comment by dblock** [comment]
I'd be down with that. If you want to contribute, check out the Rake tasks.

**Comment by dblock** [comment]
I opened #6.

**Pull request merged**
